// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"algo_assess/assess-api-server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/assess/general",
				Handler: GeneralHandler(serverCtx),
			},
		},
		rest.WithPrefix("/algo-assess/v1"),
	)
}
