// Code generated by goctl. DO NOT EDIT!
// Source: mqassess.proto

package server

import (
	"context"

	"algo_assess/assess-mq-server/internal/logic"
	"algo_assess/assess-mq-server/internal/svc"
	"algo_assess/assess-mq-server/proto"
)

type AssessMqServiceServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedAssessMqServiceServer
}

func NewAssessMqServiceServer(svcCtx *svc.ServiceContext) *AssessMqServiceServer {
	return &AssessMqServiceServer{
		svcCtx: svcCtx,
	}
}

//  获取绩效概况
func (s *AssessMqServiceServer) GetMqGeneral(ctx context.Context, in *proto.GeneralReq) (*proto.GeneralRsp, error) {
	l := logic.NewGetMqGeneralLogic(ctx, s.svcCtx)
	return l.GetMqGeneral(in)
}

//  推送行情数据--深交所
func (s *AssessMqServiceServer) PullMarketData(ctx context.Context, in *proto.MarketDataReq) (*proto.MarketDataRsp, error) {
	l := logic.NewPullMarketDataLogic(ctx, s.svcCtx)
	return l.PullMarketData(in)
}

//  推送上交所行情数据
func (s *AssessMqServiceServer) PullShMarketData(ctx context.Context, in *proto.MarketDataReq) (*proto.MarketDataReq, error) {
	l := logic.NewPullShMarketDataLogic(ctx, s.svcCtx)
	return l.PullShMarketData(in)
}

//  -----------下面的接口为调试功能，不对外开放
func (s *AssessMqServiceServer) GetAlgoOrder(ctx context.Context, in *proto.AlgoOrderReq) (*proto.AlgoOrderRsp, error) {
	l := logic.NewGetAlgoOrderLogic(ctx, s.svcCtx)
	return l.GetAlgoOrder(in)
}
