// Code generated by goctl. DO NOT EDIT.
package types

type DemoReq struct {
	Hello string `json:"hello"`
}

type DemoRsp struct {
	Reply string `json:"reply"`
}

type AssessInfo struct {
	Date  string  `json:"date"`
	Score float64 `json:"score"`
}

type Data struct {
	AlgoName   string       `json:"algo_name"`
	AssessType int          `json:"assess_type"`
	Info       []AssessInfo `json:"assess_info"`
}

type OverviewReq struct {
	BeginDate string `json:"begin_date"`
	EndDate   string `json:"end_date"`
	AlgoType  int    `json:"algo_type"`
}

type OverviewRsp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Data []Data `json:"data"`
}
