// Code generated by goctl. DO NOT EDIT.
package types

type GeneralData struct {
	TransactTime          int64   `json:"transact_time"`
	OrderQty              int64   `json:"order_qty"`
	LastQty               int64   `json:"last_qty"`
	CancelledQty          int64   `json:"cancelled_qty"`
	RejectedQty           int64   `json:"rejected_qty"`
	Vwap                  float64 `json:"vwap"`
	VwapDeviation         float64 `json:"vwap_deviation"`
	LastPrice             int64   `json:"last_price"`
	ArrivedPrice          int64   `json:"arrived_price"`
	ArrivedPriceDeviation float64 `json:"arrived_price_deviation"`
	MarketRate            float64 `json:"market_rate"`
	DealRate              float64 `json:"deal_rate"`
}

type GeneralReq struct {
	AlgoId          int32 `json:"algo_id"`
	UseculityId     int32 `json:"useculity_id"`
	TimeDemension   int32 `json:"time_demension,range=[1:6]"`
	OrderStatusType int32 `json:"order_status_type,optional"`
	StartTime       int64 `json:"start_time"`
	EndTime         int64 `json:"end_time"`
}

type GeneralRsp struct {
	Code int           `json:"code"`
	Msg  string        `json:"msg"`
	Data []GeneralData `json:"data"`
}
