// Code generated by goctl. DO NOT EDIT!
// Source: assess.proto

package server

import (
	"context"

	"algo_assess/rpc/assess/internal/logic"
	"algo_assess/rpc/assess/internal/svc"
	"algo_assess/rpc/assess/proto"
)

type AssessServer struct {
	svcCtx *svc.ServiceContext
	proto.UnimplementedAssessServer
}

func NewAssessServer(svcCtx *svc.ServiceContext) *AssessServer {
	return &AssessServer{
		svcCtx: svcCtx,
	}
}

func (s *AssessServer) GetDemo(ctx context.Context, in *proto.DemoReq) (*proto.DemoRsp, error) {
	l := logic.NewGetDemoLogic(ctx, s.svcCtx)
	return l.GetDemo(in)
}

func (s *AssessServer) GetOverview(ctx context.Context, in *proto.OverviewReq) (*proto.OverVewRsp, error) {
	l := logic.NewGetOverviewLogic(ctx, s.svcCtx)
	return l.GetOverview(in)
}
