// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	UserId      string `json:"user_id"`
	Passwd      string `json:"password"`
	ChanType    int    `json:"chan_type,default=1"`    // 1-绩效   2-管理平台
	BusPasswd   string `json:"bus_passwd,optional"`    // 总线的密码
	BusUserName string `json:"bus_user_name,optional"` // 总线用户名称
	BusAllow    int    `json:"bus_allow,optional"`     // 总线密码是否匹配
}

type LoginRsp struct {
	Code       int    `json:"code"`
	Msg        string `json:"msg"`
	Allow      int    `json:"allow"`       // 0-不允许,1-允许登陆 2-首次登陆或密码已过期，需要修改密码
	UserType   int    `json:"user_type"`   // 用户类型， 1-超级管理员，2-普通用户
	FirstLogin int    `json:"first_login"` // 是否首次登陆， 0-首次登陆 1-非首次登陆
}

type CheckPasswordReq struct {
	UserId         string `json:"user_id"`
	OriginPassword string `json:"ori_passwd"`
	ChanType       int    `json:"chan_type,default=1"` // 1-绩效   2-管理平台
}

type CheckPasswordRsp struct {
	Code   int    `json:"code"`
	Msg    string `json:"msg"`
	Result int    `json:"result"` // 1-校验成功， 非1失败
}

type UserListReq struct {
	UserName string `json:"user_name,optional"`
	ChanType int    `json:"chan_type,default=1"` // 1-绩效   2-管理平台
	Page     int32  `json:"page"`                // 当前页数
	Limit    int32  `json:"limit"`               // 每页数量
}

type UserInfos struct {
	Id         int64  `json:"id"`
	UserId     string `json:"user_id"`
	UserName   string `json:"user_name"`
	RoleId     int32  `json:"role_id"`
	RoleName   string `json:"role_name"`
	UserType   int32  `json:"user_type"` // 0-普通用户 1-超级管理员
	Status     int    `json:"status"`
	CreateTime string `json:"create_time"`
}

type UserListRsp struct {
	Code  int         `json:"code"`
	Msg   string      `json:"msg"`
	Total int64       `json:"total"`
	List  []UserInfos `json:"list"`
}

type UserModfiyReq struct {
	OperType int32  `json:"oper_type"`           // 操作类型  1-新增， 2-修改   3-删除
	UserId   string `json:"user_id,optional"`    // 用户ID  (新增必填)
	UserName string `json:"user_name,optional"`  // 用户名称 (新增必填)
	RoleId   int32  `json:"role_id,optional"`    // 角色ID (新增必填)
	RoleName string `json:"role_name,optional"`  // 角色名称 (新增必填)
	UserType int32  `json:"user_type,optional"`  // 用户类型
	Password string `json:"password,optional"`   // 密码 (新增必填)
	ChanType int    `json:"chan_type,default=1"` // 1-绩效   2-管理平台
	Status   int    `json:"status,default=1"`    // 状态，新增时，默认为1， 修改时，根据指定状态带入
}

type UserModifyRsp struct {
	Code   int    `json:"code"`
	Msg    string `json:"msg"`
	Result int32  `json:"result"` // 1--成功    2--失败
}

type UserAuthReq struct {
	UserId   string `json:"user_id"`             //用户ID
	UserType int32  `json:"user_type"`           // 用户类型 1-超级管理员，  2-其他
	ChanType int    `json:"chan_type,default=1"` // 1-绩效   2-管理平台
}

type UserAuthRsp struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
	Auth string `json:"auth"` // json化后的用户权限表
}

type RoleListReq struct {
	Scene    int    `json:"scene"`               // scene  1-角色列表  2-新增用户时，选择角色的下拉列表
	RoleId   int    `json:"role_id,optional"`    // 角色ID
	RoleName string `json:"role_name,optional"`  // 角色名称
	ChanType int    `json:"chan_type,default=1"` // 1-绩效   2-管理平台
	Page     int32  `json:"page,optional"`       // 当前页数
	Limit    int32  `json:"limit,optional"`      // 每页数量
}

type RoleInfos struct {
	Id         int64  `json:"id"`
	RoleId     int    `json:"role_id"`     // 角色ID
	RoleName   string `json:"role_name"`   // 角色名称
	RoleAuth   string `json:"role_auth"`   // 角色权限
	RoleDesc   string `json:"role_desc"`   // 角色列表展示
	Stutus     int    `json:"status"`      // 状态
	CreateTime string `json:"create_time"` // 创建时间
}

type RoleListRsp struct {
	Code  int         `json:"code"`
	Msg   string      `json:"msg"`
	Total int64       `json:"total"`
	List  []RoleInfos `json:"list"`
}

type RoleAuthReq struct {
	UserType int32 `json:"user_type,optional"`  // 用户类型 ：1-超级管理员 -2其他
	ChanType int   `json:"chan_type,default=1"` // 1-绩效   2-管理平台
}

type RoleAuthRsp struct {
	Code     int    `json:"code"`
	Msg      string `json:"msg"`
	RoleAuth string `json:"role_auth"` // json 字符串
}

type RoleModifyReq struct {
	OperType int32  `json:"oper_type"`           // 操作类型  1-新增， 2-修改   3-删除
	RoleId   int32  `json:"role_id,optional"`    // 角色ID （后台返回，自增ID）
	RoleName string `json:"role_name,optional"`  // 角色名称
	RoleAuth string `json:"role_auth,optional"`  // 角色权限列表  （json字符串)
	ChanType int    `json:"chan_type,default=1"` // 1-绩效   2-管理平台
}

type RoleModifyRsp struct {
	Code   int    `json:"code"`
	Msg    string `json:"msg"`
	Result int32  `json:"result"` // 1--成功    2--失败
}
