// Code generated by goctl. DO NOT EDIT!
// Source: router.proto

package server

import (
	"algo_assess/mq-router-server/ordproto"
	"context"

	"algo_assess/mq-router-server/internal/logic"
	"algo_assess/mq-router-server/internal/svc"
)

type RouterServiceServer struct {
	svcCtx *svc.ServiceContext
	ordproto.UnimplementedRouterServiceServer
}

func NewRouterServiceServer(svcCtx *svc.ServiceContext) *RouterServiceServer {
	return &RouterServiceServer{
		svcCtx: svcCtx,
	}
}

//  proto
func (s *RouterServiceServer) GetRouter(ctx context.Context, in *ordproto.RouterReq) (*ordproto.RouterRsp, error) {
	l := logic.NewGetRouterLogic(ctx, s.svcCtx)
	return l.GetRouter(in)
}
