// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: mqassess.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssessInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactTime          int64   `protobuf:"varint,1,opt,name=transact_time,json=transactTime,proto3" json:"transact_time,omitempty"`
	OrderQty              int64   `protobuf:"varint,2,opt,name=order_qty,json=orderQty,proto3" json:"order_qty,omitempty"`
	LastQty               int64   `protobuf:"varint,3,opt,name=last_qty,json=lastQty,proto3" json:"last_qty,omitempty"`
	CancelledQty          int64   `protobuf:"varint,4,opt,name=cancelled_qty,json=cancelledQty,proto3" json:"cancelled_qty,omitempty"`
	RejectedQty           int64   `protobuf:"varint,5,opt,name=rejected_qty,json=rejectedQty,proto3" json:"rejected_qty,omitempty"`
	Vwap                  float64 `protobuf:"fixed64,6,opt,name=vwap,proto3" json:"vwap,omitempty"`
	VwapDeviation         float64 `protobuf:"fixed64,7,opt,name=vwap_deviation,json=vwapDeviation,proto3" json:"vwap_deviation,omitempty"`
	LastPrice             int64   `protobuf:"varint,8,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	ArrivedPrice          int64   `protobuf:"varint,9,opt,name=arrived_price,json=arrivedPrice,proto3" json:"arrived_price,omitempty"`
	ArrivedPriceDeviation float64 `protobuf:"fixed64,10,opt,name=arrived_price_deviation,json=arrivedPriceDeviation,proto3" json:"arrived_price_deviation,omitempty"`
	MarketRate            float64 `protobuf:"fixed64,11,opt,name=market_rate,json=marketRate,proto3" json:"market_rate,omitempty"`
	DealRate              float64 `protobuf:"fixed64,12,opt,name=deal_rate,json=dealRate,proto3" json:"deal_rate,omitempty"`
}

func (x *AssessInfo) Reset() {
	*x = AssessInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqassess_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssessInfo) ProtoMessage() {}

func (x *AssessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mqassess_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssessInfo.ProtoReflect.Descriptor instead.
func (*AssessInfo) Descriptor() ([]byte, []int) {
	return file_mqassess_proto_rawDescGZIP(), []int{0}
}

func (x *AssessInfo) GetTransactTime() int64 {
	if x != nil {
		return x.TransactTime
	}
	return 0
}

func (x *AssessInfo) GetOrderQty() int64 {
	if x != nil {
		return x.OrderQty
	}
	return 0
}

func (x *AssessInfo) GetLastQty() int64 {
	if x != nil {
		return x.LastQty
	}
	return 0
}

func (x *AssessInfo) GetCancelledQty() int64 {
	if x != nil {
		return x.CancelledQty
	}
	return 0
}

func (x *AssessInfo) GetRejectedQty() int64 {
	if x != nil {
		return x.RejectedQty
	}
	return 0
}

func (x *AssessInfo) GetVwap() float64 {
	if x != nil {
		return x.Vwap
	}
	return 0
}

func (x *AssessInfo) GetVwapDeviation() float64 {
	if x != nil {
		return x.VwapDeviation
	}
	return 0
}

func (x *AssessInfo) GetLastPrice() int64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

func (x *AssessInfo) GetArrivedPrice() int64 {
	if x != nil {
		return x.ArrivedPrice
	}
	return 0
}

func (x *AssessInfo) GetArrivedPriceDeviation() float64 {
	if x != nil {
		return x.ArrivedPriceDeviation
	}
	return 0
}

func (x *AssessInfo) GetMarketRate() float64 {
	if x != nil {
		return x.MarketRate
	}
	return 0
}

func (x *AssessInfo) GetDealRate() float64 {
	if x != nil {
		return x.DealRate
	}
	return 0
}

type GeneralReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlgoId          int32 `protobuf:"varint,1,opt,name=algo_id,json=algoId,proto3" json:"algo_id,omitempty"`
	UseculityId     int32 `protobuf:"varint,2,opt,name=useculity_id,json=useculityId,proto3" json:"useculity_id,omitempty"`
	TimeDemension   int32 `protobuf:"varint,3,opt,name=time_demension,json=timeDemension,proto3" json:"time_demension,omitempty"`
	OrderStatusType int32 `protobuf:"varint,4,opt,name=order_status_type,json=orderStatusType,proto3" json:"order_status_type,omitempty"`
	StartTime       int64 `protobuf:"varint,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime         int64 `protobuf:"varint,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
}

func (x *GeneralReq) Reset() {
	*x = GeneralReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqassess_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralReq) ProtoMessage() {}

func (x *GeneralReq) ProtoReflect() protoreflect.Message {
	mi := &file_mqassess_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralReq.ProtoReflect.Descriptor instead.
func (*GeneralReq) Descriptor() ([]byte, []int) {
	return file_mqassess_proto_rawDescGZIP(), []int{1}
}

func (x *GeneralReq) GetAlgoId() int32 {
	if x != nil {
		return x.AlgoId
	}
	return 0
}

func (x *GeneralReq) GetUseculityId() int32 {
	if x != nil {
		return x.UseculityId
	}
	return 0
}

func (x *GeneralReq) GetTimeDemension() int32 {
	if x != nil {
		return x.TimeDemension
	}
	return 0
}

func (x *GeneralReq) GetOrderStatusType() int32 {
	if x != nil {
		return x.OrderStatusType
	}
	return 0
}

func (x *GeneralReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *GeneralReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GeneralRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Info []*AssessInfo `protobuf:"bytes,3,rep,name=info,proto3" json:"info,omitempty"`
}

func (x *GeneralRsp) Reset() {
	*x = GeneralRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqassess_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeneralRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralRsp) ProtoMessage() {}

func (x *GeneralRsp) ProtoReflect() protoreflect.Message {
	mi := &file_mqassess_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralRsp.ProtoReflect.Descriptor instead.
func (*GeneralRsp) Descriptor() ([]byte, []int) {
	return file_mqassess_proto_rawDescGZIP(), []int{2}
}

func (x *GeneralRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GeneralRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GeneralRsp) GetInfo() []*AssessInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type MarketDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UseculityId   int32  `protobuf:"varint,1,opt,name=useculity_id,json=useculityId,proto3" json:"useculity_id,omitempty"`         // 证券ID
	SecId         string `protobuf:"bytes,2,opt,name=sec_id,json=secId,proto3" json:"sec_id,omitempty"`                            // 证券代码
	EntrustBidVol uint64 `protobuf:"varint,3,opt,name=entrust_bid_vol,json=entrustBidVol,proto3" json:"entrust_bid_vol,omitempty"` // 委托买入数量
	EntrustAskVol uint64 `protobuf:"varint,4,opt,name=entrust_ask_vol,json=entrustAskVol,proto3" json:"entrust_ask_vol,omitempty"` // 委托买出数量
	OrgiTime      uint64 `protobuf:"varint,5,opt,name=orgi_time,json=orgiTime,proto3" json:"orgi_time,omitempty"`                  // 数据生成时间
	TotalTradeVol uint64 `protobuf:"varint,6,opt,name=total_trade_vol,json=totalTradeVol,proto3" json:"total_trade_vol,omitempty"` // 成交总量
	LastPrice     uint64 `protobuf:"varint,7,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`               // 最新价格
}

func (x *MarketDataReq) Reset() {
	*x = MarketDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqassess_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDataReq) ProtoMessage() {}

func (x *MarketDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_mqassess_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDataReq.ProtoReflect.Descriptor instead.
func (*MarketDataReq) Descriptor() ([]byte, []int) {
	return file_mqassess_proto_rawDescGZIP(), []int{3}
}

func (x *MarketDataReq) GetUseculityId() int32 {
	if x != nil {
		return x.UseculityId
	}
	return 0
}

func (x *MarketDataReq) GetSecId() string {
	if x != nil {
		return x.SecId
	}
	return ""
}

func (x *MarketDataReq) GetEntrustBidVol() uint64 {
	if x != nil {
		return x.EntrustBidVol
	}
	return 0
}

func (x *MarketDataReq) GetEntrustAskVol() uint64 {
	if x != nil {
		return x.EntrustAskVol
	}
	return 0
}

func (x *MarketDataReq) GetOrgiTime() uint64 {
	if x != nil {
		return x.OrgiTime
	}
	return 0
}

func (x *MarketDataReq) GetTotalTradeVol() uint64 {
	if x != nil {
		return x.TotalTradeVol
	}
	return 0
}

func (x *MarketDataReq) GetLastPrice() uint64 {
	if x != nil {
		return x.LastPrice
	}
	return 0
}

type MarketDataRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // 返回码
}

func (x *MarketDataRsp) Reset() {
	*x = MarketDataRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mqassess_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarketDataRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDataRsp) ProtoMessage() {}

func (x *MarketDataRsp) ProtoReflect() protoreflect.Message {
	mi := &file_mqassess_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDataRsp.ProtoReflect.Descriptor instead.
func (*MarketDataRsp) Descriptor() ([]byte, []int) {
	return file_mqassess_proto_rawDescGZIP(), []int{4}
}

func (x *MarketDataRsp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_mqassess_proto protoreflect.FileDescriptor

var file_mqassess_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x71, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6d, 0x71, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x22, 0xa6, 0x03, 0x0a, 0x0a, 0x41,
	0x73, 0x73, 0x65, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x51, 0x74, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x6c,
	0x61, 0x73, 0x74, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6c,
	0x61, 0x73, 0x74, 0x51, 0x74, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x6c, 0x65, 0x64, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63,
	0x61, 0x6e, 0x63, 0x65, 0x6c, 0x6c, 0x65, 0x64, 0x51, 0x74, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x72,
	0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x71, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x65, 0x64, 0x51, 0x74, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x76, 0x77, 0x61, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x76, 0x77,
	0x61, 0x70, 0x12, 0x25, 0x0a, 0x0e, 0x76, 0x77, 0x61, 0x70, 0x5f, 0x64, 0x65, 0x76, 0x69, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0d, 0x76, 0x77, 0x61, 0x70,
	0x44, 0x65, 0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6c,
	0x61, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x72, 0x72, 0x69,
	0x76, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x61, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a,
	0x17, 0x61, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x64,
	0x65, 0x76, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x15,
	0x61, 0x72, 0x72, 0x69, 0x76, 0x65, 0x64, 0x50, 0x72, 0x69, 0x63, 0x65, 0x44, 0x65, 0x76, 0x69,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f,
	0x72, 0x61, 0x74, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x65, 0x61, 0x6c, 0x5f, 0x72,
	0x61, 0x74, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x64, 0x65, 0x61, 0x6c, 0x52,
	0x61, 0x74, 0x65, 0x22, 0xd5, 0x01, 0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x6c, 0x67, 0x6f, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x6c, 0x67, 0x6f, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x75,
	0x73, 0x65, 0x63, 0x75, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x63, 0x75, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x25,
	0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x64, 0x65, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x6d, 0x65,
	0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x0a, 0x11, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x5c, 0x0a, 0x0a, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12,
	0x28, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x6d, 0x71, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0xfd, 0x01, 0x0a, 0x0d, 0x4d, 0x61,
	0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x0c, 0x75,
	0x73, 0x65, 0x63, 0x75, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x63, 0x75, 0x6c, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x15,
	0x0a, 0x06, 0x73, 0x65, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x73, 0x65, 0x63, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x65, 0x6e, 0x74, 0x72, 0x75, 0x73, 0x74,
	0x5f, 0x62, 0x69, 0x64, 0x5f, 0x76, 0x6f, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d,
	0x65, 0x6e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x42, 0x69, 0x64, 0x56, 0x6f, 0x6c, 0x12, 0x26, 0x0a,
	0x0f, 0x65, 0x6e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x5f, 0x61, 0x73, 0x6b, 0x5f, 0x76, 0x6f, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x65, 0x6e, 0x74, 0x72, 0x75, 0x73, 0x74, 0x41,
	0x73, 0x6b, 0x56, 0x6f, 0x6c, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x72, 0x67, 0x69, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6f, 0x72, 0x67, 0x69, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x74, 0x72, 0x61, 0x64,
	0x65, 0x5f, 0x76, 0x6f, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x56, 0x6f, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09,
	0x6c, 0x61, 0x73, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x23, 0x0a, 0x0d, 0x4d, 0x61, 0x72,
	0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x91,
	0x01, 0x0a, 0x0f, 0x41, 0x73, 0x73, 0x65, 0x73, 0x73, 0x4d, 0x71, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4d, 0x71, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x6c, 0x12, 0x14, 0x2e, 0x6d, 0x71, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x2e, 0x47, 0x65,
	0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x6d, 0x71, 0x61, 0x73, 0x73,
	0x65, 0x73, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x6c, 0x52, 0x73, 0x70, 0x12, 0x42,
	0x0a, 0x0e, 0x50, 0x75, 0x6c, 0x6c, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x17, 0x2e, 0x6d, 0x71, 0x61, 0x73, 0x73, 0x65, 0x73, 0x73, 0x2e, 0x4d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x6d, 0x71, 0x61, 0x73,
	0x73, 0x65, 0x73, 0x73, 0x2e, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x73, 0x70, 0x42, 0x07, 0x5a, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_mqassess_proto_rawDescOnce sync.Once
	file_mqassess_proto_rawDescData = file_mqassess_proto_rawDesc
)

func file_mqassess_proto_rawDescGZIP() []byte {
	file_mqassess_proto_rawDescOnce.Do(func() {
		file_mqassess_proto_rawDescData = protoimpl.X.CompressGZIP(file_mqassess_proto_rawDescData)
	})
	return file_mqassess_proto_rawDescData
}

var file_mqassess_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_mqassess_proto_goTypes = []interface{}{
	(*AssessInfo)(nil),    // 0: mqassess.AssessInfo
	(*GeneralReq)(nil),    // 1: mqassess.GeneralReq
	(*GeneralRsp)(nil),    // 2: mqassess.GeneralRsp
	(*MarketDataReq)(nil), // 3: mqassess.MarketDataReq
	(*MarketDataRsp)(nil), // 4: mqassess.MarketDataRsp
}
var file_mqassess_proto_depIdxs = []int32{
	0, // 0: mqassess.GeneralRsp.info:type_name -> mqassess.AssessInfo
	1, // 1: mqassess.AssessMqService.GetMqGeneral:input_type -> mqassess.GeneralReq
	3, // 2: mqassess.AssessMqService.PullMarketData:input_type -> mqassess.MarketDataReq
	2, // 3: mqassess.AssessMqService.GetMqGeneral:output_type -> mqassess.GeneralRsp
	4, // 4: mqassess.AssessMqService.PullMarketData:output_type -> mqassess.MarketDataRsp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mqassess_proto_init() }
func file_mqassess_proto_init() {
	if File_mqassess_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mqassess_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssessInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqassess_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneralReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqassess_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeneralRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqassess_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mqassess_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarketDataRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mqassess_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mqassess_proto_goTypes,
		DependencyIndexes: file_mqassess_proto_depIdxs,
		MessageInfos:      file_mqassess_proto_msgTypes,
	}.Build()
	File_mqassess_proto = out.File
	file_mqassess_proto_rawDesc = nil
	file_mqassess_proto_goTypes = nil
	file_mqassess_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AssessMqServiceClient is the client API for AssessMqService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AssessMqServiceClient interface {
	// 获取绩效概况
	GetMqGeneral(ctx context.Context, in *GeneralReq, opts ...grpc.CallOption) (*GeneralRsp, error)
	// 推送行情数据
	PullMarketData(ctx context.Context, in *MarketDataReq, opts ...grpc.CallOption) (*MarketDataRsp, error)
}

type assessMqServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAssessMqServiceClient(cc grpc.ClientConnInterface) AssessMqServiceClient {
	return &assessMqServiceClient{cc}
}

func (c *assessMqServiceClient) GetMqGeneral(ctx context.Context, in *GeneralReq, opts ...grpc.CallOption) (*GeneralRsp, error) {
	out := new(GeneralRsp)
	err := c.cc.Invoke(ctx, "/mqassess.AssessMqService/GetMqGeneral", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *assessMqServiceClient) PullMarketData(ctx context.Context, in *MarketDataReq, opts ...grpc.CallOption) (*MarketDataRsp, error) {
	out := new(MarketDataRsp)
	err := c.cc.Invoke(ctx, "/mqassess.AssessMqService/PullMarketData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssessMqServiceServer is the server API for AssessMqService service.
type AssessMqServiceServer interface {
	// 获取绩效概况
	GetMqGeneral(context.Context, *GeneralReq) (*GeneralRsp, error)
	// 推送行情数据
	PullMarketData(context.Context, *MarketDataReq) (*MarketDataRsp, error)
}

// UnimplementedAssessMqServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAssessMqServiceServer struct {
}

func (*UnimplementedAssessMqServiceServer) GetMqGeneral(context.Context, *GeneralReq) (*GeneralRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMqGeneral not implemented")
}
func (*UnimplementedAssessMqServiceServer) PullMarketData(context.Context, *MarketDataReq) (*MarketDataRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullMarketData not implemented")
}

func RegisterAssessMqServiceServer(s *grpc.Server, srv AssessMqServiceServer) {
	s.RegisterService(&_AssessMqService_serviceDesc, srv)
}

func _AssessMqService_GetMqGeneral_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessMqServiceServer).GetMqGeneral(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mqassess.AssessMqService/GetMqGeneral",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessMqServiceServer).GetMqGeneral(ctx, req.(*GeneralReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _AssessMqService_PullMarketData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarketDataReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssessMqServiceServer).PullMarketData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mqassess.AssessMqService/PullMarketData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssessMqServiceServer).PullMarketData(ctx, req.(*MarketDataReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _AssessMqService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mqassess.AssessMqService",
	HandlerType: (*AssessMqServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMqGeneral",
			Handler:    _AssessMqService_GetMqGeneral_Handler,
		},
		{
			MethodName: "PullMarketData",
			Handler:    _AssessMqService_PullMarketData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mqassess.proto",
}
