// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"account-auth/account-auth-server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Cors},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/auth/login",
					Handler: LoginHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/rolelist",
					Handler: RoleListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/role-auth",
					Handler: RoleAuthHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/role-modify",
					Handler: RoleModifyHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/user-list",
					Handler: AuthUserListHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/user-modify",
					Handler: UserModifyHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/check-password",
					Handler: CheckPasswordHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/auth/user-auth",
					Handler: UserAuthHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/algo-assess/v1"),
	)
}
